version: '3'

services:
  odp-mysql:
    container_name: odp-mysql
    hostname: odp-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_PASSWORD=mysql
      - MYSQL_USER=mysql
    healthcheck:
      test: "mysqladmin ping"
      interval: "10s"
      timeout: "10s"
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: "./mysql/docker-entrypoint-initdb.d"
        target: "/docker-entrypoint-initdb.d"
      - type: bind
        source: "./mysql/var/lib/mysql-files"
        target: "/var/lib/mysql-files"

  odp-postgres:
    container_name: odp-postgres
    hostname: odp-postgres
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: "pg_isready -U \"${POSTGRES_USER:-postgres}\" || exit 1"
      interval: "10s"
      timeout: "10s"
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: "./postgres/docker-entrypoint-initdb.d"
        target: "/docker-entrypoint-initdb.d"

  odp-java:
    container_name: odp-java
    build:
      context: java
      dockerfile: Dockerfile
    hostname: odp-java
    image: odp-java
    healthcheck:
      test: "embulk --version"
      interval: "10s"
      timeout: "10s"
    volumes:
      - type: bind
        source: "../oss-data-platform-embulk"
        target: "/var/apps/embulk"
    command: |
      bash -c "
        cd /var/apps/embulk/bundle
        embulk bundle
        /usr/sbin/sshd -D
      "

  odp-airflow:
    platform: linux/amd64
    container_name: odp-airflow
    build:
      context: airflow
      dockerfile: Dockerfile
    hostname: odp-airflow
    image: odp-airflow
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CLI__ENDPOINT_URL=http://localhost:8080
      - AIRFLOW__CORE__DAGS_FOLDER=/var/apps/airflow/dags
      - AIRFLOW__CORE__DEFAULT_TIMEZONE=Asia/Tokyo
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__PLUGINS_FOLDER=/var/apps/airflow/plugins
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql://mysql:mysql@odp-mysql:3306/airflow
      - AIRFLOW__LOGGING_BASE_LOG_FOLDER=/var/apps/airflow/logs
      - AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT=False
      - AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL=10
      - AIRFLOW__WEBSERVER__BASE_URL=http://localhost:8080
      - AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE=Asia/Tokyo
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
      - AIRFLOW__WEBSERVER__RELOAD_ON_PLUGIN_CHANGE=True
      - AIRFLOW__WEBSERVER__WARN_DEPLOYMENT_EXPOSURE=False
      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT:8080
    healthcheck:
      test: "curl -f http://localhost:8080/health"
      interval: "10s"
      timeout: "10s"
    depends_on:
      odp-mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: "../oss-data-platform-airflow"
        target: "/var/apps/airflow"

  odp-python3:
    platform: linux/amd64
    container_name: odp-python3
    build:
      context: python3
      dockerfile: Dockerfile
    hostname: odp-python3
    image: odp-python3
    healthcheck:
      test: "curl -f http://localhost:8080"
      interval: "10s"
      timeout: "10s"
    ports:
      - "8888:8080"
    volumes:
      - type: bind
        source: "../oss-data-platform-dbt"
        target: "/var/apps/dbt"
    command: |
      bash -c "
        /usr/sbin/sshd
        cd /var/apps/dbt
        dbt docs generate --profiles-dir ./profiles
        dbt docs serve    --profiles-dir ./profiles
      "
