version: '3'

services:
  odp-mysql:
    container_name: odp-mysql
    hostname: odp-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_PASSWORD=mysql
      - MYSQL_USER=mysql
    healthcheck:
      test: "mysqladmin ping"
      interval: "10s"
      timeout: "10s"
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: "./mysql/docker-entrypoint-initdb.d"
        target: "/docker-entrypoint-initdb.d"
      - type: bind
        source: "./mysql/var/lib/mysql-files"
        target: "/var/lib/mysql-files"

  odp-postgres:
    container_name: odp-postgres
    hostname: odp-postgres
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: "pg_isready -U \"${POSTGRES_USER:-postgres}\" || exit 1"
      interval: "10s"
      timeout: "10s"
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: "./postgres/docker-entrypoint-initdb.d"
        target: "/docker-entrypoint-initdb.d"
